manip:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 150
        
    joint1_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint_1
        pid: {p: 150, i: 90, d: 30}
        
    joint2_position_controller:
        type: effort_controllers/JointPositionController
        joint: joint_2
        pid: {p: 20, i: 10, d: 2}
